import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { cookies, headers } from "next/headers";
import { detectLocaleFromAcceptLanguage, type Locale } from "@/lib/i18n";
import RootClientShell, { LanguageSwitcher } from "./root-client-shell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

async function resolveLocaleOnServer(): Promise<Locale> {
  const cookieStore = await cookies();
  const cookieLocale = cookieStore.get("locale")?.value;
  if (cookieLocale === "ru" || cookieLocale === "en") return cookieLocale;

  const headerStore = await headers();
  const acceptLanguage = headerStore.get("accept-language");
  return detectLocaleFromAcceptLanguage(acceptLanguage);
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await resolveLocaleOnServer();

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootClientShell initialLocale={locale}>
          <div className="mx-auto max-w-2xl px-4 pt-6 flex justify-end">
            <LanguageSwitcher />
          </div>

          {children}
        </RootClientShell>
      </body>
    </html>
  );
}
